import networkx as nx

#тут просто устанавливаем свзять между точками
def short_way(x):
    DG = nx.DiGraph()
    DG.add_edge('p28', 'p27', weight=1)
    DG.add_edge('p27', 'p26', weight=1)
    DG.add_edge('p26', 'p25', weight=1)
    DG.add_edge('p25', 'p22', weight=1)
    DG.add_edge('p24', 'p22', weight=1)
    DG.add_edge('p23', 'p22', weight=1)
    DG.add_edge('p22', 'p21', weight=1)
    DG.add_edge('p21', 'p20', weight=1)
    DG.add_edge('p20', 'p29', weight=2)
    DG.add_edge('p29', 'p7', weight=2)
    DG.add_edge('p7', 'p6', weight=2)
    DG.add_edge('p17', 'p16', weight=1)
    DG.add_edge('p15', 'p16', weight=1)
    DG.add_edge('p14', 'p15', weight=1)
    DG.add_edge('p13', 'p15', weight=1)
    DG.add_edge('p16', 'p18', weight=1)
    DG.add_edge('p18', 'p19', weight=1)
    DG.add_edge('p19', 'p9', weight=1)
    DG.add_edge('p9', 'p8', weight=1)
    DG.add_edge('p8', 'p6', weight=1)
    DG.add_edge('p6', 'p5', weight=1)
    DG.add_edge('p5', 'p4', weight=1)
    DG.add_edge('p4', 'p3', weight=1)
    DG.add_edge('p3', 'p2', weight=1)
    DG.add_edge('p2', 'p1', weight=1)
    DG.add_edge('p1', 'p0', weight=1)
    nx.draw_networkx(DG)
    print(nx.shortest_path(DG, x, 'p0'))

    return nx.shortest_path(DG, x, 'p0')
